version: 2
jobs:
 build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.10.0
    steps:
      - checkout
      - run:
          command: |
            set -eux -o pipefail
            sudo apt-get -qq update
            sudo apt-get install -y awscli
      - deploy:
          name: deploy
          command: |
            set -eux -o pipefail
            if [ "${CIRCLE_BRANCH}" = "S3staticsite" ]; then
            aws s3 sync /home/ubuntu/S3ContinuousDeploy s3://s3awscicd --delete
            else
            echo "Not master branch, dry run only"
            fi
