version: 2
jobs:
 build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.10.0
    steps:
      - checkout
      - run:
          command: |
            set -eux -o pipefail
            sudo apt-get -qq update
            sudo apt-get install -y awscli
      - deploy:
          name: deploy
          command: |
            set -eux -o pipefail
            aws configure set default.s3.signature_version s3v4
            if [ "${CIRCLE_BRANCH}" = "s3staticsite" ]; then
              aws s3 sync . s3://s3awscicd --delete --region ap-south-1
            else
              echo "Not master branch, dry run only"
            fi
